package io.pleo.antaeus.core.common.exceptions

class NetworkException : Exception("A network error happened please try again.")
